-- DESAFIO 9
-- CRIAÇÃO DE USUÁRIOS E PERMISSÕES

select * from user;

-- CRIAÇÃO DO USUÁRIO "WILLIAM" E SUA "SENHA"

CREATE USER 'william'@'localhost' IDENTIFIED BY 'enterprise1';


-- NA SENTENÇA ABAIXO, IREI CONCEDER A PERMISSÃO DE SOMENTE LEITURA (SELECT)
-- A LEITURA SERÁ POSSÍVEL EM TODAS AS TABELAS DO BANCO DE DADOS "PROJETOS_EMPRESA"

GRANT SELECT ON projetos_empresa.* TO 'william'@'localhost';

-- SEGUNDA ETAPA

-- CRIAÇÃO DO USUÁRIO "LUIZA" E SUA "SENHA"

CREATE USER 'luiza'@'localhost' IDENTIFIED BY 'enterprise2';


-- NA SENTENÇA ABAIXO, SERÃO CONCEDIDAS OUTRAS PERMISSÕES, COMO:
-- LEITURA (SELECT), INSERÇÃO (INSERT) E MODIFICAÇÃO (UPDATE) 
-- EM TODAS AS TABELAS DO BANCO "PROJETOS_EMPRESA"

GRANT SELECT, INSERT, UPDATE ON projetos_empresa.* TO 'luiza'@'localhost';

-- AGORA, O USUÁRIO "LUIZA" TEM PERMISSÕES PARA LER, INSERIR E MODIFICAR DADOS NA PROJETOS_EMPRESA
-- PORÉM, NÃO PODE EXCLUIR REGISTROS

-- TERCEIRA ETAPA
-- CONCEDER AS PERMISSÕES

FLUSH PRIVILEGES;




